---
name: Lint
run-name: Linting
on:
  check_suite:
    types: [completed]
  push: {}
  pull_request: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: deadnix
        run: "nix-shell -p deadnix --run 'deadnix .'"
      - name: statix
        run: "nix-shell -p statix --run 'statix check'"
      - name: nixfmt
        run: "nix-shell -p treefmt nixfmt-rfc-style --run 'treefmt --no-cache --fail-on-change'"
